#!/bin/bash

set -eu

: ${SOLAR_DIR:=/usr/lib/solar-eclipse}

if [ "${SOLAR_BIN:-}" = "" ]
then
    export SOLAR_BIN=${SOLAR_DIR}/bin
fi

if [ -z "${SOLAR_LIB:-}" ]
then
    export SOLAR_LIB=${SOLAR_DIR}/lib
fi

export PATH=$SOLAR_BIN:$PATH
export SOLAR_PROGRAM_NAME=$0

if [ ! -s "$SOLAR_BIN/solarmain" ]
then
    echo "The directory $SOLAR_BIN contains no solarmain executable"
else
    "$SOLAR_BIN/solarmain" "$@"
fi
